/* Main.c file generated by New Project wizard
 * 
 * Created:   Tue Apr 21 2026
 * Processor: LPC1114FBD48/301
 * Compiler:  GCC for ARM
 */
 /*Name : tasneem sobhi alsady
 ID:220210489*/

/* Define hardware register addresses for GPIO Port 0 and Port 2 */
#define GPIO0DIR (*((volatile unsigned long *)0x50008000)) 
#define GPIO0DATA (*((volatile unsigned long *)0x50003FFC)) 
#define GPIO2DIR (*((volatile unsigned long *)0x50028000)) 
#define GPIO2DATA (*((volatile unsigned long *)0x50023FFC))

int i = 0; 

/*  delay function to allow LCD to process instructions */
void delay(int count) { 
    for(i = 0; i <= count; i++); 
}

/* Function to send commands to the LCD in 4-bit mode */
void send_cmd(unsigned char cmd) { 
    /* Send the High Nibble (upper 4 bits) of the command */
    GPIO2DATA = (cmd >> 4);      // Shift bits to reach PIO2_0 to PIO2_3 pins
    GPIO0DATA = 0b100;           // Set RS=0 (Command) and E=1 (Enable pulse)
    delay(1000); 
    GPIO0DATA = 0b000;           // Set E=0 to complete the pulse
    delay(1000); 

    /* Send the Low Nibble (lower 4 bits) of the command */
    GPIO2DATA = (cmd & 0x0F);    // Mask to extract only the lower 4 bits
    GPIO0DATA = 0b100;           // Set E=1 (Enable pulse)
    delay(1000); 
    GPIO0DATA = 0b000;           // Set E=0 to complete the pulse
    delay(1000); 
} 

/* Function to send data/letters to the LCD in 4-bit mode */
void send_letter(unsigned char letter) { 
    /* Send the High Nibble of the character */
    GPIO2DATA = (letter >> 4); 
    GPIO0DATA = 0b110;           // Set RS=1 (Data) and E=1 (Enable pulse)
    delay(1000); 
    GPIO0DATA = 0b010;           // Set E=0
    delay(1000); 

    /* Send the Low Nibble of the character */
    GPIO2DATA = (letter & 0x0F); 
    GPIO0DATA = 0b110;           // Set E=1 (Enable pulse)
    delay(1000); 
    GPIO0DATA = 0b010;           // Set E=0
    delay(1000); 
} 

/* Function to send a full string of characters */
void send_string(char* string) { 
    while(*string != '\0') {     // Loop until the end of string null character
        send_letter(*string);    // Send current character
        string++;                // Move to the next character in memory
    } 
} 

int main (void) { 
    /* Hardware Initialization  */
    GPIO0DIR |= 0b110;           // Set PIO0_1 (RS) and PIO0_2 (E) as Outputs
    GPIO2DIR |= 0x0F;           // Set PIO2_0 to PIO2_3 as Outputs for data bus
    
    GPIO0DATA = 0;               // Clear Port 0 data
    GPIO2DATA = 0;               // Clear Port 2 data
 
    delay(20000);                // Power-on wait (more than 15ms)

    /* 4-bit mode initialization sequence */
    GPIO2DATA = 0x03;
    GPIO0DATA = 0b100; 
     delay(100);
    GPIO0DATA = 0; 
    delay(5000);
    GPIO2DATA = 0x03; 
    GPIO0DATA = 0b100; 
    delay(100);
    GPIO0DATA = 0;
    delay(100);
    GPIO2DATA = 0x03;
    GPIO0DATA = 0b100; 
    delay(100); 
    GPIO0DATA = 0; 
    delay(100);
    GPIO2DATA = 0x02; 
    GPIO0DATA = 0b100; 
    delay(100); 
    GPIO0DATA = 0; 
    delay(100); // Switch to 4-bit

    /* Final LCD configuration commands */
    send_cmd(0x28);              // Set Function: 4-bit mode, 2 lines, 5x7 dots
    send_cmd(0x0C);              // Display Control: Display ON, Cursor OFF
    send_cmd(0x01);              // Clear Display command
    delay(5000);                 // Wait for clear display to complete
    send_cmd(0x06);              // Entry Mode: Increment cursor automatically

    /* Lab Task 1: Write Name and Student ID */
    send_string("Tasneem Al-Sady");
    
    send_cmd(0xC0);              // Move cursor to the beginning of the second line
    send_string("220210489");

    while (1);                   // Infinite loop to keep the display active
    return 0; 
}
